name: Linux Tests
on: [push]

jobs:
  basic-test:
    name: tests on linux
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install valgrind
        run: sudo apt-get install valgrind

      - name: Build basic test
        run: make -C test

      - name: Execute basic test
        run: ./test/*.out

      - name: Execute basic test with valgrind
        run: valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes --error-exitcode=1 ./test/*.out
