name: MacOS Tests
on: [push]

jobs:
  basic-test:
    name: tests on macos
    runs-on: macos-catalina-10.15.7

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install 42 norminette
        run: python3 -m pip install --upgrade pip setuptools && python3 -m pip install norminette

      - name: install francinette
        run: bash -c "$(curl -fsSL https://raw.github.com/xicodomingues/francinette/master/bin/install.sh)"

      - name: Execute francinette
        run: sudo bash $HOME/francinette/tester.sh

      - name: Execute francinette strict
        run: sudo bash $HOME/francinette/tester.sh -s

      - name: Build basic test
        run: make -C test

      - name: Execute basic test
        run: ./test/*.out
