name: MacOS Tests
on: [push]

jobs:
  basic-test:
    name: tests on macos
    runs-on: macos-11

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install 42 norminette
        run: python3 -m pip install --upgrade pip setuptools && python3 -m pip install norminette

      - name: Install tripouille tester
        run: git clone https://github.com/Tripouille/gnlTester.git

      - name: Execute 42 norminette
        run: norminette

      - name: Execute tripouille tester
        run: make -C gnlTester a

      - name: Build basic test
        run: make -C test

      - name: Execute basic test
        run: ./test/*.out
