name: MacOS Tests
on: [push]

jobs:
  basic-test:
    name: tests on macos
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: install francinette
        run: bash -c "$(curl -fsSL https://raw.github.com/xicodomingues/francinette/master/bin/install.sh)"

      - name: Execute francinette
        run: paco

      - name: Execute francinette strict
        run: paco -s

      - name: Build basic test
        run: make -C test

      - name: Execute basic test
        run: ./test/a.out
