name: Windows Tests
on: [push]

jobs:
  basic-test:
    name: tests on windows
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build basic test
        run: make -C test

      - name: Execute basic test
        run: ./test/*.exe